### ISSUE TITLE
Fix link to pg8000 on the Japanese Wikipedia

### ISSUE THREAD

**Issue by tlocke** [tlocke/pg8000#103]
The link for pg8000 on https://ja.wikipedia.org/wiki/PostgreSQL is out of date and should be https://github.com/tlocke/pg8000 instead. I can't read Japanese and so I can't edit it myself, but could a Japanese speaker help out by editing it? Thanks! I had a look through the people who have starred pg8000 and have a Japanese location and it seems that @yukkeorg, @hirocob or @kwilczynski may be able to help?

**Comment by yan12125** [comment]
I updated it! I'm not a speaker of Japanese, just currently learning :)

**Comment by tlocke** [comment]
Brilliant, thanks @yan12125 !
