### ISSUE TITLE
How to check for failed commit

### ISSUE THREAD

**Issue by durzo** [tlocke/pg8000#107]
I just went down the rabbit hole of #36 and reading the postgres mailing list archives where the patch ultimately stalled and went nowhere.

In that thread they describe clients being able to track and determine if the silent ROLLBACK on COMMIT has happened - is there a way to do this in pg8000?

I am having serious issues not being able to detect this silent rollback in my code and am considering switching to another library, which I really don't want to do :(

**Comment by tlocke** [comment]
Hi @durzo, this should be fixed in release 1.29.0. I've reopened https://github.com/tlocke/pg8000/issues/36 where I go into more detail about pg8000's approach to the problem, so I'll close this issue now.

**Comment by durzo** [comment]
Many thanks @tlocke
