### ISSUE TITLE
Support for "COPY from" using a buffer

### ISSUE THREAD

**Issue by bnaoki** [tlocke/pg8000#108]
Hi there! From the docs, I see that it's possible to do a COPY from stdin using the documented method below:

```python
>>> # Create a CSV file in memory
>>>
>>> stream_in = StringIO()
>>> csv_writer = csv.writer(stream_in)
>>> csv_writer.writerow([1, "electron"])
12
>>> csv_writer.writerow([2, "muon"])
8
>>> csv_writer.writerow([3, "tau"])
7
>>> stream_in.seek(0)
0
>>>
>>> # Create a table and then copy the CSV into it
>>>
>>> con.run("CREATE TEMPORARY TABLE lepton (id SERIAL, name TEXT)")
>>> con.run("COPY lepton FROM STDIN WITH (FORMAT CSV)", stream=stream_in)
```

I wanted to ask if it would be possible to write into the stream some set size chunk by chunk instead of all at once like in the example. My use case is that I have a very large number of rows in parquet format (10-100 million), and I am wanting to not have to load the entire CSV stream into memory at once. Currently, I'm planning to use pyarrow for reading in the file in chunks.

Does the current API support this? If so, would you mind giving me some pointers on how to go about doing so? I looked around Python's StringIO, streaming, and csv writer docs as I'm somewhat new to the Python ecosystem but did not find any useful info around this. Thank you!

**Comment by tlocke** [comment]
Hi @bnaoki, there wasn't really a good way of doing this, but I thought there really should be, so in release 1.28.0 the `stream` parameter can now be an iterable (either binary chunks or text lines). The second example at https://github.com/tlocke/pg8000#copy-from-and-to-a-stream should be similar to what you're looking for. Let me know how you get on!

**Comment by bnaoki** [comment]
Tried this out today and got it working. Thanks again!

My code ended up looking something like the following:
```python
import pyarrow.dataset as ds

def csv_stream(source: Path) -> Generator[bytes, None, None]:
    dataset = ds.dataset(source, format="parquet")

    for batch in dataset.to_batches():
        buffer = io.BytesIO()
        csv.write_csv(
            batch,
            buffer,
            write_options=csv.WriteOptions(
                include_header=False,
            ),
        )
        yield buffer.getvalue()
        buffer.close()


con.run("COPY table_1 FROM STDIN WITH (FORMAT CSV)",
    stream=csv_stream("file1.parquet"),
)
```

As a side note, I initially tried to yield the buffer object directly i.e.
```python
    for batch in dataset.to_batches():
        buffer = io.BytesIO()
        csv.write_csv(
            batch,
            buffer,
            write_options=csv.WriteOptions(
                include_header=False,
            ),
        )
        buffer.seek(0)
        yield buffer
        buffer.close()
```

...but I was getting the following exception in `_send_message` of `core.py`:
> TypeError: object of type '_io.BytesIO' has no len()

Is this expected? Are `BytesIO` not intended to be passed in directly?

**Comment by tlocke** [comment]
To answer your question, the `BytesIO` object represents an I/O stream, so it can't be used as an item in the iterable that is given to pg8000, because for that, pg8000 expects items to be of type `str` or binary, eg `bytes` or `bytearray`.

Also, looking at your code, I'd have thought it would be possible to do something like:

```
import pyarrow.dataset as ds

def csv_stream(source):
    dataset = ds.dataset(source, format="parquet")

    for batch in dataset.to_batches():
        yield batch.to_pandas().to_csv()
```

You'd have to work out the right flags to use for omitting the title row etc.

**Comment by bnaoki** [comment]
Makes sense, thanks. 👍

Regarding `.to_pandas().to_csv()`, I think that could work too but I assumed it would be slower. I didn't actually check, but I think both due to the `to_csv()` itself as well as the unnecessary conversion to `to_pandas()`.
