### ISSUE TITLE
`identifier()` breaks for system objects

### ISSUE THREAD

**Issue by bnaoki** [tlocke/pg8000#110]
The following code errors with `relation "pg_catalog.pg_tables" does not exist`.

```python
table = "pg_catalog.pg_table"

for row in con.run(f"SELECT * FROM {identifier(table)}"):
        print(row)
```

This is because `identifier("pg_catalog.pg_table")` returns `"pg_catalog.pg_table"` which Postgres is apparently not happy about. Perhaps it should return `"pg_catalog"."pg_table"` instead?

**Comment by tlocke** [comment]
Hi @bnaoki, I think there are two possible cases here. The first is if there's a table called pg_table in the pg_catalog schema, then there are two identifiers and so you would escape them by doing:

```
schema = "pg_catalog"
table = "pg_table"

for row in con.run(f"SELECT * FROM {identifier(schema)}.{identifier(table)}"):
        print(row)
```

The second case is when there's a table called "pg_catalog.pg_table" in the default schema, in which case you'd escape it by doing:

```
table = "pg_catalog.pg_table"

for row in con.run(f"SELECT * FROM {identifier(table)}"):
        print(row)
```

**Comment by bnaoki** [comment]
Ahh right, that makes sense. My case was for the former -- the system reserved `pg_*` schemas. Thanks you for the explanation. I'll go ahead and close this.
