### ISSUE TITLE
Malformed array literal

### ISSUE THREAD

**Issue by vanviegen** [tlocke/pg8000#115]
pg8000 encodes strings within arrays containing carriage return and newline characters without double quotes. For example `["a", "\r\n", "b"]` gets encoded as `'{"a",\r\n,"\b"}'`.  That'll throw a `ProgrammingError` with `'M': 'malformed array literal: "{"a",\r\n,"\b"}"`.

The right encoding is: `'{"a","\r\n","\b"}'`.

**Comment by tlocke** [comment]
Thanks for the bug report and patch @vanviegen, I've used the patch in https://github.com/tlocke/pg8000/commit/3d7b5bb768e997a612be08ede389e76d104ec2d4 with a few tweaks that I hope you agree with :-)
