### ISSUE TITLE
channel_binding error

### ISSUE THREAD

**Issue by fawaf** [tlocke/pg8000#119]
not sure where/why this error is occuring: `The channel_binding parameter must be None if channel binding is not required`. i am creating the connection with all the defaults, as below

on the latest 1.29.2 release

```
pg8000.native.Connection(
        user,
        host=host,
        database=db,
        password=password,
        ssl_context=True,
    )
```

**Comment by tlocke** [comment]
Hi @fawaf, I think this is a bug that's fixed with a release I've just made with version number 1.29.3. Let me know if it's still a problem though.
