### ISSUE TITLE
Allow arbitrary paramters

### ISSUE THREAD

**Issue by asomethings** [tlocke/pg8000#121]
It seems like Arbitrary paramters were introduced at [v1.14.0](https://github.com/tlocke/pg8000/commit/357a3c31b0d885e51706365ad859004902ad5319) and removed right away at [v1.15.0](https://github.com/tlocke/pg8000/commit/bd22eb6b5b438e467d2609c49a17ba672d3d91a1).

Today, I was trying to establish a connection to pg with timezone parameter which was impossible since there were no arbitrary paramteres allowed. 

By any chance, could Arbitrary paramters be re-introduced?

Timezone parameter would make me satisfy but postgresql has a bunch of [connection arguments](https://www.postgresql.org/docs/14/runtime-config-client.html#RUNTIME-CONFIG-CLIENT-STATEMENT) so I think arbitrary paramters could be better

**Comment by tlocke** [comment]
Hi @asomethings, could you do something like:
```
import pg8000.native

con = pg8000.native.Connection("postgres", password="cpsnow")
con.run("SET TIME ZONE 'Europe/Rome';")

```

**Comment by asomethings** [comment]
@tlocke It is working but for me it seems like running a query for each connection seems like a bad practice for me. But anyways it's working and thanks for the help!

**Comment by asomethings** [comment]
@tlocke Okay got it, No problems with it! Closing the issue
