### ISSUE TITLE
Returning results in other forms than tuples.

### ISSUE THREAD

**Issue by allaboutmikey** [tlocke/pg8000#122]
This has been asked before ( #11 ), but I have code! If you are willing to look at this feature, I can create a pull request.
The code is minimal (+2 in dbapi.py and -1+4 in core.py) and has exactly zero impact if the feature is not used.

It allows you to submit a row_factory function as a parameter when making a connection. This row_factory is called with the column info from context.columns and the original result tuple just before it is appended to context.rows. It can then use those to create and substitute a dict (or what ever other type/class/structure is returned by the function) for the original tuple. This allows code written for other dbapi drivers with this feature to be used unchanged. 
Some of them have a dict factory built in, I have not included this, but it would only be another line or two. Once the (for example) dict_factory function is passed in, calls to fetch* return the rows in dict format instead of tuples. This has no impact if not used and works well in my testing. I don't think it would have any effect on dbapi compliance. Most of the drivers I have used have a similar feature (psycopg, sqlite, python-tds for example).

**Comment by allaboutmikey** [comment]
FYI, here is the row_factory i use to return dict rows.
```
def dict_factory(cols, row):
     return dict((cols[idx]['name'], value) for idx, value in enumerate(row))
```

**Comment by tlocke** [comment]
Hi @allaboutmikey, pg8000 aims to be as minimal as possible, and so if something can be done by building on top of pg8000, then I'm reluctant to include it. Here's my [guiding quote from Liedtke](https://en.m.wikipedia.org/wiki/Microkernel#Essential_components_and_minimality)  (it talks about microkernels, but I think it still applies)

> A concept is tolerated inside the microkernel only if moving it outside the kernel, i.e., permitting competing implementations, would prevent the implementation of the system's required functionality.

Sorry to be such a curmudgeon 🙂

**Comment by allaboutmikey** [comment]
Apologies @tlocke , I thought I had replied to this back in November.

I understand your reluctance to get caught up in feature bloat. My counter arguments are:
1. This *is* a very minimal and simple change (+5 lines)
2. No effect on dbapi2 compliance.
3. If the feature is unused, the only extra code executed is the check that it wasn't. So no big performance hit.
4. Code compatibility. Other drivers have this (including standard library sqlite3 driver) so with this patch, switching to pg8000 requires no code changes for those who use row factories (doesn't everyone like dictionaries? :) ).

I think that argument 3 means that implementing the row conversion outside pg8000 fails the required functionality test. This patch is a way of *allowing* competing functionality for returned rows without messing up the calling program.

Anyway, this is your baby, so I will of course respect your decision and just patch locally for myself if you choose not to include it. Thanks for writing such a cool project.
