### ISSUE TITLE
i am porting this driver to dart

### ISSUE THREAD

**Issue by insinfo** [tlocke/pg8000#123]
I'm implementing a postgreSQL driver in pure dart lang, I'm basing myself on your implementation, I would like to know if you authorize me to use the same name?

https://github.com/insinfo/pg8000

**Comment by tlocke** [comment]
Hi @insinfo, good luck with the porting project, hope it goes well. On the naming, I think it's best to use a different name so that it doesn't confuse Google?

**Comment by insinfo** [comment]
I hadn't thought about Google Search indexing, I'm not very good with names, I accept suggestions.

Thank you very much for your work.

**Comment by tlocke** [comment]
What about calling it **Dargres** ?
