### ISSUE TITLE
Django Backend

### ISSUE THREAD

**Issue by jkugler** [tlocke/pg8000#126]
Hello, I'm reviving https://github.com/mfenniak/pg8000/issues/102

It would be nice if a Django backend for pg8000 could be developed. I did find https://github.com/generalpiston/django-pygresql but its last update was nine years ago.

Is there any chance a Django backend could be made a part of this project? Or a sister project? The author of pg8000 would probably be the most qualified to do this, as they know the code best.

Is there any interest from the community?

**Comment by tlocke** [comment]
Hi @jkugler, for my part I think this is a good idea, but I think it would work best as a separate project.

**Comment by tlocke** [comment]
There's now Django backend available at https://pypi.org/project/django-pg8000/

**Comment by jkugler** [comment]
Fantastic, thanks!
