### ISSUE TITLE
User of pg8000 here

### ISSUE THREAD

**Issue by jacobamarshall** [tlocke/pg8000#13]
Hello,

I've been using pg8000 and wanted to both thank the team and log my use cases.  Since pg8000 is pure python, it allows me to use it in AWS Lambda functions without any extra work.  Other C-based libraries require pre-compiling and other steps to work in that environment.  No issues so far on my end, thanks again for the great library.

Jacob

**Comment by ngvirus** [comment]
what kind of authentication you use for your lambdas? password or iam?

**Comment by jacobamarshall** [comment]
Password right now because I'm under a time crunch- but ideally will move to iam in the future for more security.

**Comment by ngvirus** [comment]
well with pg8000 it doesn't work 😢

**Comment by ngvirus** [comment]
why is that closed? is it fixed or?

**Comment by tlocke** [comment]
The problem with IAM authentication has been raised at https://github.com/tlocke/pg8000/issues/14
