### ISSUE TITLE
Unable to run tests locally

### ISSUE THREAD

**Issue by kurtmckee** [tlocke/pg8000#130]
When running the tests locally, I found that my locale did not match any of the locales listed in `tests/native/test_typeconversion.py`. As a result, `CURRENCY` was not set and resulted in a `NameError` getting raised when that file was imported by pytest.

This can be fixed by setting a default value for `CURRENCY`.

**Comment by tlocke** [comment]
Thanks for your bug report and patch @kurtmckee I think the bug is fixed with https://github.com/tlocke/pg8000/commit/00308aa285743e1df4b9920239a68e3db1af8006
