### ISSUE TITLE
fetchmany(size=...) fetches full result set

### ISSUE THREAD

**Issue by kukushking** [tlocke/pg8000#133]
Hi folks, by the looks of it `fetchmany(size=...)` fetches full result set where `size` parameter only controls the number of rows to return from the iterator. We'd like to be able to fetch limited result set to be able to handle large datasets w/o running out of memory. 

https://github.com/aws/aws-sdk-pandas/issues/2230

**Comment by tlocke** [comment]
Hi @kukushking, my quick answer is to use [server side cursors](https://github.com/tlocke/pg8000#id12) , but I'll give a fuller response later on when I have some time.

**Comment by kukushking** [comment]
Thanks I will have a look! Would be awesome to have a cursor class similar to pymysql's [SSCursor](https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.SSCursor) that would take care of the specific commands to manipulate server-side cursors
