### ISSUE TITLE
Missing git tag for release 1.29.8

### ISSUE THREAD

**Issue by jayaddison** [tlocke/pg8000#135]
Hi @tlocke - it looks like the `git` tag for v1.29.8 might be missing?  (I see the information about that version in the release notes, but can't find the commit for it).

**Comment by tlocke** [comment]
Thanks for spotting that @jayaddison, should be fixed now. I'm afraid it's not the first time I've missed it out :-)

**Comment by jayaddison** [comment]
All good :)  Thank you!
