### ISSUE TITLE
Parameterizing Query Fails

### ISSUE THREAD

**Issue by Infrared1029** [tlocke/pg8000#140]
Not sure why does this fail
```python
SELECT COUNT(*) FROM 
(SELECT BTRIM(
    REPLACE(
        REPLACE(
            REPLACE(
                REPLACE(
                    flags::TEXT,
                    $$'$$, '"'),
                    'None', 'null'),
                    'True', 'true'),
                    'False', 'false'),
               '"' )::JSONB as d1
FROM "Table1" INNER JOIN "Table2" ON "Table1"."user_id"="Table2"."id" WHERE email NOT LIKE :email_0) as sub_1
```

`{'S': 'ERROR', 'V': 'ERROR', 'C': '42601', 'M': 'syntax error at or near "%"', 'P': '422', 'F': 'scan.l', 'L': '1180', 'R': 'scanner_yyerror'}`
`[parameters: ('%outlook.com',)]`

**Comment by tlocke** [comment]
Hi @Infrared1029, thanks for the bug report. That should be fixed now in version 1.30.2. The problem was that pg8000 wasn't handling dollar-quoted strings properly.
