### ISSUE TITLE
pg8000 not updated in conda for over a year

### ISSUE THREAD

**Issue by schaffino** [tlocke/pg8000#147]
I'm looking to use pg8000 as a dependency in a conda package and have discovered due to a dependency i have on a more recent cloud-sql-python-connector version, that i need pg8000 >= 1.30.3. It looks like pg8000 stopped getting published in conda-forge over a year ago. Is there any way to get the package publish synced up again?

Many thanks

**Comment by tlocke** [comment]
Hi @schaffino, I'm afraid I don't know how cond-forge works, I'd suggest getting in touch with the people at conda?
