### ISSUE TITLE
Regression: non-ASCII login breaks connection since 1.30.3

### ISSUE THREAD

**Issue by radioxoma** [tlocke/pg8000#155]
Hello! Looks like commit 796cd014e248963002b70368008141ea32e49307 breaks connection if login contains non-ASCII symbols.

      File "test_pg.py", line 118, in test_version
        con = pg8000.native.Connection(**config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "venv/lib/python3.12/site-packages/pg8000/native.py", line 195, in __init__
        super().__init__(*args, **kwargs)
      File "venv/lib/python3.12/site-packages/pg8000/core.py", line 383, in __init__
        self.message_types[code](_read(self._sock, data_len - 4), context)
      File "venv/lib/python3.12/site-packages/pg8000/core.py", line 853, in handle_PARAMETER_STATUS
        key, value = data[:pos].decode("ascii"), data[pos + 1 : -1].decode("ascii")
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 1: ordinal not in range(128)

An `parameter_statuses` example from last working version 1.30.3:

    data = deque(
        [
            (b"application_name", b""),
            (b"client_encoding", b"UTF8"),
            (b"DateStyle", b"ISO, DMY"),
            (b"integer_datetimes", b"on"),
            (b"IntervalStyle", b"postgres"),
            (b"is_superuser", b"off"),
            (b"server_encoding", b"UTF8"),
            (b"server_version", b"10.23 (Ubuntu 10.23-0ubuntu0.18.04.2)"),
            (
                b"session_authorization",
                b'\xd0\xa0\xd1\x8b\xd0\xb6\xd0\xb8\xd0\xb9',  # An redhead "Рыжий"
            ),
            (b"standard_conforming_strings", b"on"),
            (b"TimeZone", b"Europe/Moscow"),
        ],
        maxlen=100,
    )

**Comment by tlocke** [comment]
Thanks for the bug report @radioxoma, that should be fixed now in version 1.31.2

**Comment by radioxoma** [comment]
Thank you for a fast response!
