### ISSUE TITLE
Autocommit false causing locks (?)

### ISSUE THREAD

**Issue by EralpB** [tlocke/pg8000#16]
Hello, I'm using the default autommit false mode and I've a lot of cursors opening and closing implicity with the "with" tag, I wonder if the following use is correct with no commits. Does closing a cursor, commit the transaction? I'm experiencing some db locks and not sure what's the root cause.

```
pgsql = SimpleLazyObject(lambda: pg8000.connect(
    user=SETTINGS['PGSQL']['USER'],
    password=SETTINGS['PGSQL']['PASSWORD'],
    host=SETTINGS['PGSQL']['HOST'],
    port=SETTINGS['PGSQL']['PORT'],
    database=SETTINGS['PGSQL']['DATABASE'],
    ssl=SETTINGS['PGSQL']['SSL'],
))


        with pgsql.cursor() as cursor:
            cursor.execute(
                """
                SELECT first_name, picture, username
                FROM accounts_user
                WHERE id = %s
                """,
                (user_id,),
            )
            a,b,c = cursor.fetchone()
        print('do other stuff')
        # hundreds other with pgsql.cursor()..s
```

All my SQLs are SELECT statements.

**Comment by tlocke** [comment]
Hi @EralpB, closing the cursor in pg8000 doesn't actually do anything. In the default autocommit mode which you're using, the `cursor.execute` method will automatically start a new transaction (if one isn't in progress already). If you stick to a single connection per thread, and avoid long-running transactions (by calling `connection.rollback` or `connection.commit` when you can), I've found that's the best bet for avoiding locks.
