### ISSUE TITLE
https://pythonhosted.org/pg8000/ needs update

### ISSUE THREAD

**Issue by yan12125** [tlocke/pg8000#2]
Hi, great to see a new release and a new repo. Just a question: https://pythonhosted.org/pg8000/ still points to http://github.com/mfenniak/pg8000/. Could you update it?

**Comment by tlocke** [comment]
Hi @yan12125, the uploading of documentation to pythonhosted.org is no longer supported, and the documentation is out of date. The only option is to delete it, which I have now done. The documentation is now the README file in the GitHub repository:

https://github.com/tlocke/pg8000#pg8000

**Comment by yan12125** [comment]
Thank you very much! I'm going to update my links to point to this repo.
