### ISSUE TITLE
Parameterized SQL statements

### ISSUE THREAD

**Issue by bombillazo** [tlocke/pg8000#23]
First off, I really like the pg8000 package! Been using it for Aurora-PSQL and Redshift.

The only big stopper I've had so far comes when parameterizing parts fo the query besides SELECTs, WHEREs or INSERTs/UPDATEs.

For example, having `SELECT TOP :amount * FROM ...` does not work.
Neither does `... WHERE id = 100 LIMIT :amount`.

Is there a way pg8000 could support parameterizing other parts of the query?

**Comment by riamaria** [comment]
@bombillazo I'm new to pg8000, but I do recommend replying with some test code in here (the actual `cursor.execute` call).

**Comment by pavbis** [comment]
@bombillazo try 
`pg8000.paramstyle = "named"`
and then 
`cursor.execute('SELECT * FROM bar WHERE foo > :foo', {"foo": 3})`

**Comment by tlocke** [comment]
Hi @bombillazo, whether or not a part of the query can be parameterized or not depends on the server, not pg8000. So for me running PostgreSQL 10.10 the following works:

```
>>> cursor.execute("SELECT 'silo 1' limit %s", ((2),))
<pg8000.core.Cursor object at ...>
>>> cursor.fetchone()
['silo 1']
```
