### ISSUE TITLE
SSL connections don't verify server name

### ISSUE THREAD

**Issue by JonathanRRogers** [tlocke/pg8000#24]
Python standard library function ssl.wrap_socket() is deprecated because it doesn't handle server host names. Since pg8000 uses that function, it can't properly secure connections to Postgres. In contrast, psycopg2 exposes libpq's "sslmode" parameter, which when set to "verify-full" verifies server hostname.

**Comment by tlocke** [comment]
I've taken a slightly different approach to solve this https://github.com/tlocke/pg8000/commit/8aa2ea70aaaafafbb26246c78c1a8f3f33c251e0 let me know what you think :-)

**Comment by JonathanRRogers** [comment]
> I've taken a slightly different approach to solve this [8aa2ea7](https://github.com/tlocke/pg8000/commit/8aa2ea70aaaafafbb26246c78c1a8f3f33c251e0) let me know what you think :-)

The new ssl_context parameter works for me. Do you have any idea when a new version of pg8000 will be released?
