### ISSUE TITLE
Parametrized strings crashe with error pg8000.core.ProgrammingError

### ISSUE THREAD

**Issue by viktor-mitin** [tlocke/pg8000#26]
Hi,
I'm Using PG8000 pg8000==1.12.5, and in the case when Parametrized strings are passed into curr.execute(sql, query_params) it crashes with the next exception.

pg8000.core.ProgrammingError: {'S': 'ERROR', 'V': 'ERROR', 'C': '42601', 'M': 'syntax error at or near "$2"', 'P': '16', 'F': 'scan.l', 'L': '1128', 'R': 'scanner_yyerror'}

Thanks

**Comment by tlocke** [comment]
Hi @viktor-mitin, could you give a Minimal Reproducible Example please?

https://stackoverflow.com/help/minimal-reproducible-example

Thanks 🙂
