### ISSUE TITLE
PostgreSQL json_agg, row_to_json

### ISSUE THREAD

**Issue by pavbis** [tlocke/pg8000#29]
While executing of the following statement on the sql side, I receive well formatted json array 

```
DROP TABLE IF EXISTS users;

CREATE TEMPORARY TABLE IF NOT EXISTS "users"
(
  "firstName"  varchar(255) not null,
  "lastName"  varchar(255) not null
);

INSERT INTO users VALUES ('max', 'mega');
INSERT INTO users VALUES ('lisa', 'rapid');

SELECT json_agg(json_strip_nulls(row_to_json(u)))
FROM (
    SELECT
        "firstName",
        "lastName"
    FROM users
 ) u
```

Result:

`[{"firstName":"max","lastName":"mega"}, {"firstName":"lisa","lastName":"rapid"}]`

If I execute the same statement in the service layer (via cursor) the result contains incorrect json quotes, basically a python list of dicts:

`[{'firstName':'max','lastName':'mega'}, {'firstName':'lisa','lastName':'rapid'}]`

Is there any possibility to retrieve the same result as SQL returns?

**Comment by pavbis** [comment]
@tlocke , ping.

**Comment by tlocke** [comment]
Hi @pavbis, pg8000 will do a `json.loads()` on a JSON type, so what gets returned are Python objects. So that explains the output when you print it.
