### ISSUE TITLE
Support for Postgresql Refcursors

### ISSUE THREAD

**Issue by pzdump** [tlocke/pg8000#3]
Hi,

Is it possible with pg8000 to use postgresql refcursors?

I have multiple functions returning refcursors, pg8000 just returns the cursor name using cursor.fetchall() in this case it's 'clientcur'

In squirrelSQL (using jdbc under the hood) for example to fetch the date from a refcursor one would do a "fetch all from clientcur" after the psql function call.

Thanks

**Comment by tlocke** [comment]
Hi @pzdump, are you trying to do something like this:

````
>>> cursor.execute("""
...    CREATE FUNCTION reffunc(refcursor) RETURNS refcursor AS $$
...    BEGIN
...        OPEN $1 FOR SELECT 'atto';
...        RETURN $1;
...    END;
...    $$ LANGUAGE plpgsql;""")
>>> cursor.execute("begin")
>>> cursor.execute("SELECT reffunc('funccursor')")
>>> cursor.execute("fetch all from funccursor")
>>> res = cursor.fetchall()
>>> print(res)
(['atto'],)
```

I tried the above code and it worked as I expected.

**Comment by pzdump** [comment]
Hi @tlocke,
I try to fetch data using functions, returning them as ref cursor.
The reason for the ref cursor ist, to pass arbitrary result sets through functions.
This is the only way in postgres to pass resultsets with proper types, much like a view, where you dont have to define every column beforehand and still have proper column types.

(The example function you used, specifies on "how to supply the cursors name", which is not the problem.)

Suppose a function like this:

```CREATE FUNCTION reffunc2() RETURNS refcursor AS '
DECLARE
    clientcur refcursor;
BEGIN
    OPEN clientcur FOR SELECT a,b,c from test;
    RETURN clientcur;
END;
' LANGUAGE plpgsql;
```


Now this function returns a open query e.g. a state of the select statement used, whose resultset the caller could fetch with

```SQL
begin;
select * from reffunc2();
fetch all from clientcur
```

The Python level `cursor.fetchall()` in this case just returns the name of the cursor, but not the resultset.
The correct behaviour would be to return the rows selected from table test, not the cursors name (in your case attos, in my sample clientcur.
SquirrelSQL for example opens 2 tabs by doing that, the select returning just the name of the cursor ('clientcur'), and the 2nd tab for fetch all from clientcur, which yields the actual rows of the select stored in the refcursor.

If you need a better example let me know. :-)

**Comment by tlocke** [comment]
In your example you have an unbound cursor, that means the cursor name will be generated by the server. With an unbound cursor you could do something like:

```
>>> cursor.execute("""
...     CREATE FUNCTION reffunc2() RETURNS refcursor AS $$
...     DECLARE
...         clientcur refcursor;
...     BEGIN
...         OPEN clientcur FOR SELECT 'atto';
...         RETURN clientcur;
...     END;
...     $$ LANGUAGE plpgsql;""")
>>> cursor.execute("begin")
>>> cursor.execute("SELECT reffunc2()")
>>> name = cursor.fetchone()[0]
>>> print(name)
<unnamed portal 1>
>>> cursor.execute('fetch all from "' + name + '"')
>>> res = cursor.fetchall()
>>> print(res)
(['atto'],)
```

Alternatively you can use a bound cursor, in which case the cursor name takes the same name as the variable used. For example:

```
>>> cursor.execute("""
...     CREATE FUNCTION reffunc() RETURNS refcursor AS $$
...     DECLARE
...         clientcur CURSOR FOR SELECT 'atto';
...     BEGIN
...         OPEN clientcur;
...         RETURN clientcur;
...     END;
...     $$ LANGUAGE plpgsql;""")
>>> cursor.execute("begin")
>>> cursor.execute("SELECT reffunc()")
>>> cursor.execute("fetch all from clientcur")
>>> res = cursor.fetchall()
>>> print(res)
(['atto'],)
```

Is that the sort of thing you were looking for?

**Comment by pzdump** [comment]
Hi,
no, see the updated post, it was wrong at first, seems you startet answering before the update.

The topic is really confusing if you didn't work with the refcursor cases before, i try to explain as good as i can.

A unbound cursor declaration does not mean it's name is necessarily auto generated.
Names are almost always generated if not specified. Unbound refers to not being declared with a query.
See here for better explanation: http://www.postgresqltutorial.com/plpgsql-cursor/

> Because unbound cursor variable is not bounded to any query when we declared it, we have to specify the query when we open it. See the following example:
`OPEN my_cursor FOR SELECT * FROM city WHERE counter = p_country;`

So, a cursor will almost always be unbound, because it would only be bound to a query if you knew that query already at DECLARE time. If you have  dynamic query, say a dynamic where clause, it must be unbound, because you bind with the generated query somewhere in your function code.


Your example doesn't do anything, just opening a cursor with nothing attached.
The question is about "how to retrieve data from the cursor" using pg8000.


See my updated post above.
In this example, the cursor really is bound to a executed statement.
It now has a "state", or maybe better, it points to a result set which was selected.
(with the "SELECT a,b,c from test"

The declare
`    clientcur REFCURSOR := 'clientcur';';`
makes sure it's name will be clientcur instead of some <unnamed portal x>.

```
>>> cursor.execute("fetch all from clientcur")
>>> res = cursor.fetchall()
>>> print(res)
```
Now i tried this back in january, and the print always returns
a list with a single element, which contains the refcursors name not that data.

But it should return the result set of the cursor's query instead, which can be thouands of rows.
Provided the cursor is bound to a query and executed of course.

So that should be whatever select you did with the open command:
OPEN my_cursor FOR SELECT * FROM city WHERE counter = p_country;`

In the example, from the website it should return rows from the city table.
Pgadmin, squirrel sql and dbeaver work this way.
So the fetch all from <> syntax kind of pulls the data from the clientcursor, which is unique during the transaction.

If that doesn't help you much, i can work out a complete example in the next days, when i can access my postgres server.

Let me know. :-)

Thank you.

regards,
Pieter

**Comment by tlocke** [comment]
Yes, I think that a complete example of where pg8000 goes wrong would be a great help.

**Comment by pzdump** [comment]
I think we can close the issue, upon further inspection i noticed it works.
Maybe the version i had back then had a bug.

Still adding the complete example ... for others wanting to use ref cursors.


Suppose this function being deployed to database

```SQL
CREATE OR REPLACE FUNCTION GetResultsAsRefcursor()
	RETURNS REFCURSOR
	LANGUAGE 'plpgsql'
	AS $BODY$
	DECLARE clientcur REFCURSOR := 'clientcur';--
	BEGIN
		OPEN clientcur FOR EXECUTE 'select table_name, table_schema from information_schema.tables where table_schema=''pg_catalog''';--
		RETURN clientcur;--
	END;--
	$BODY$;
```

This can be queried with
```PYTHON
>>> cursor = conn.cursor()
>>> cursor.execute("begin;")
>>> cursor.execute("select * from GetResultsAsRefcursor();")
>>> cursor.execute("fetch all from clientcur;")
>>> cursor.fetchall()
(['pg_aggregate', 'pg_catalog'], ['pg_am', 'pg_catalog'], ['pg_amop', 'pg_catalog'], ['pg_amproc', 'pg_catalog'], ['pg_attrdef', 'pg_catalog'], ['pg_attribute', 'pg_catalog']
```

Please note that you must start a transaction with begin; first.
And the "fetch all from clientcur;" is needed too.

If you just do the function execute you will just receive the name of the ref cursor, e.g. so:
```PYTHON
>>> cursor.execute("select * from GetResultsAsRefcursor();")
>>> cursor.fetchall()
(['clientcur'],)
```

**Comment by tlocke** [comment]
Great, glad it's working 🙂
