### ISSUE TITLE
Unclear how to switch from ssl to ssl_context option

### ISSUE THREAD

**Issue by fschulze** [tlocke/pg8000#30]
When some settings which have been moved to init_params are None, then the connection call fails. This wasn't an issue before when all kwargs were named explicitly and had None as default. Looks like this is caused by the change for #8.
Filtering init_params for None values should fix it.

**Comment by fschulze** [comment]
I guess I misread the changelog. This seems to be the backward incompatible change it is talking about. Unfortunately the docs don't make it very clear how to adapt to the change.

**Comment by tlocke** [comment]
I think you're right that for the init_params, any that have a value of None should be ignored. So I've done a new release that has that behavior.

So, with switching from `ssl` to `ssl_context` the docs on the [connect function](https://github.com/tlocke/pg8000#pg8000connectuser-hostlocalhost-source_addressnone-unix_socknone-port5432-passwordnone-ssl_contextnone-timeoutnone-tcp_keepalivetrue-init_params) should explain things. But let me know if these docs aren't clear and we can reword it etc.

**Comment by fschulze** [comment]
In case you want to add to the docs, here are the arguments of ``wrap_socket`` and their equivalent now:
``ca_certs``: ``context = ssl.create_default_context(cafile=ca_certs)``
``keyfile``, ``certfile``: ``context.load_cert_chain(certfile, keyfile)``
For the rest I don't know if they would make sense at all.

**Comment by JonathanRRogers** [comment]
BTW, devpi now uses the new interface: devpi/devpi#783
