### ISSUE TITLE
TypeError: can't concat bool to bytes

### ISSUE THREAD

**Issue by titan550** [tlocke/pg8000#31]
I started getting this error with version 1.14.0+ when I try to connect to Redshift. The problem disappears when I install version 1.13.2. Tested on Python 3.8.2 and 3.6.9

It is likely because of [this commit](https://github.com/tlocke/pg8000/commit/357a3c31b0d885e51706365ad859004902ad5319).

Error:
```
  File "~\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pg8000\__init__.py", line 48, in connect
    return Connection(
  File "~\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pg8000\core.py", line 1408, in __init__
    val.extend(k.encode('ascii') + NULL_BYTE + v + NULL_BYTE)
TypeError: can't concat bool to bytes
```

**Comment by tlocke** [comment]
Hi @titan550, I've done a new release 1.15.0 which should give a better error message. Without seeing the function call of `connect()` I'm not sure what's causing the problem, but my guess is that you used to use `ssl=True`. The `ssl` argument is no longer used, there's an `ssl_context` instead. The docs should explain how to use `ssl_context`.
