### ISSUE TITLE
COPY BINARY for easier bulk inserts

### ISSUE THREAD

**Issue by Downchuck** [tlocke/pg8000#34]
Over in the MySQL land and SQLAlchemy they're passing INSERT statements through to executemany and running a nasty regex to see if it's a bulk operation.

The execute(statement, stream=file_obj) for pg8000 works really well as an alternative, but it's not fun to hand-craft the file_obj.  The postgresql binary format is pretty simple for execute, this could allow an iterator or list of tuples.

See COPY BINARY:
https://www.postgresql.org/docs/12/sql-copy.html

**Comment by Downchuck** [comment]
Some other workarounds -- shove it all in via a thick JSON packet:
https://bytes.vokal.io/20160516-psycopg2-bulk-inserts/

String replace an INSERT INTO into a COPY command with CSV format:
```
            sql_copy = sql_template.replace("INSERT INTO ", "COPY ")
            sql_copy = sql_copy[0:sql_template.find(" VALUES ")] + " FROM STDIN WITH (FORMAT CSV)"
            with StringIO() as text:
                writer = csv.writer(text)
                writer.writerows(rows)
                with BytesIO(text.getvalue().encode("utf-8")) as stream:
                    cur.connection.cursor().execute(sql_copy, stream=stream)
```

**Comment by tlocke** [comment]
Hi @Downchuck, as I understand it you're trying to insert data as fast as possible. COPY seems like the fastest method, and I've put a note on it in the docs:

https://github.com/tlocke/pg8000#copy-from-and-to-a-file

As I understand it, there's not much difference in speed between the COPY formats (text, CSV and binary), but do correct me if I'm wrong. However, the text and CSV formats are much easier to create than the binary format. So I'd go for COPY using the text or CSV format, creating the stream with something like:

```
stream = BytesIO()
for serial, name in ((1, 'electron'), (2, 'muon'), (3, 'tau')):
    stream.write(b'\t'.join((str(serial).encode(), name.encode())) + b'\n')
stream.seek(0)
```

**Comment by Downchuck** [comment]
Note that text separation falls apart with free form text, that is, text which may have a tab in it. The CSV method isn't ideal for bigger amounts of data but works well enough.

**Comment by tlocke** [comment]
That's a good point. I've changed the example to use the CSV format https://github.com/tlocke/pg8000#copy-from-and-to-a-file

Maybe we should offer more support for the binary format though? Some sort of helper function perhaps?

**Comment by Downchuck** [comment]
Yes, a small helper function would handle things well. If I get a chance I'll write it and revisit this in a month or three.

**Comment by tlocke** [comment]
I'll close this now, as we've got a CSV solution.
