### ISSUE TITLE
Recognize user password as parameter

### ISSUE THREAD

**Issue by danizen** [tlocke/pg8000#35]
### DESIRED BEHAVIOR

I would want the following to work, obviously with paramstyle set to 'format', as it does for psycopg2:

```python
# get the username and password for a new user from AWS secrets manager ...
# now create the user
sql = 'CREATE USER {} WITH PASSWORD %s".format(username)
with dbconn.cursor() as cursor:
    cursor.execute(sql, [password])
```

### BACKGOUND

I am using pg8000 to avoid a binary dependence so I can easily build an AWS Lambda on a windows desktop without using Docker.  The purpose of the AWS Lambda is to a Custom CloudFormation resource, so that in CloudFormation, users may:
 * Create an Master username and password
 * Create an application specific username and password
 * Create an RDS database
 * Provision the RDS database so that the application specific username and password
   exists, and has access to a list of databases

### WHY IMPORTANT

I see the main use case for pg8000 is to avoid a need to build psycopg2 in situations where it is unnecessary, and maybe to enable the use of the SOCKS protocol because pure Python's own sockets are used.

Instead of code similar to the above, I have to build a string containing the actual password, which adds complexities I'd prefer to avoid:
* Test the password to insist it uses only allowed character classes *or* properly encode these myself
* Bypass an intermediate logging mechanism (a cursor wrapper) that logs the sql.

**Comment by tlocke** [comment]
Hi @danizen, I'm afraid that with the PostgreSQL server some SQL statements can't be parameterized. See https://github.com/tlocke/pg8000#many-sql-statements-cant-be-parameterized

Although it appears to work with psycopg2, I'd expect that in fact the full SQL statement would appear in the logs. Let us know if you find any different though.

One workaround may be to disable logging, then execute the statement, then enable logging again. See https://dba.stackexchange.com/questions/94625/how-do-i-hide-sensitive-information-like-plaintext-passwords-from-the-logs
