### ISSUE TITLE
adaptation/type casting support

### ISSUE THREAD

**Issue by srepmub** [tlocke/pg8000#38]
hi,

we are looking for a pure-python alternative to psycopg2, but we need support for custom type adaptation/casting. it's not clear (at first glance) from the pg8000 documentation if this is possible with pg8000. it doesn't seem too hard to support in any case..? :)

looking at the alternatives, pygresql at least seems to support this:

https://www.pygresql.org/contents/pgdb/adaptation.html#typecasting-to-python

it would be great if the documentation could in any case be updated with a statement about such support.

**Comment by tlocke** [comment]
Hi @srepmub, thanks for your interest in pg8000. At the moment there's no support within pg8000 for custom types. However, I can see a place in pg8000 for custom types, as it's something that's difficult to efficiently implement on top of pg8000. As they say of microkernels:

> A concept is tolerated inside the microkernel only if moving it outside the kernel, i.e., permitting competing implementations, would prevent the implementation of the system's required functionality.

The same applies to database drivers. In this case I think that custom types outside the driver would be too inefficient, so in principle I think we should have custom types in pg800.

So, do you have any thoughts about how we should go about this?

**Comment by srepmub** [comment]
for now, I just update connection.pg_types and connection.py_types, and that makes it work for our custom (geometry) types. so just:

_connection.pg_types[oid] = (pg8000.core.FC_BINARY, geometry_recv)
_connection.py_types[Polygon] = (oid, pg8000.core.FC_BINARY, geometry_send) # for all geometry types, such as Point etc

this is enough for our purposes, but it might be nicer of course to add a little convenience api to pg8000 like psycopg2 has. it would also be nice if we could register a Geometry base class somehow (as with psycopg2), instead of having to register each sub-class.

**Comment by tlocke** [comment]
Ingenious! I'm thinking of dropping the FC_BINARY option and having everything FC_TEXT. What do you think of that idea?

**Comment by srepmub** [comment]
I'm afraid I don't know enough about the pg8000 internals to comment on that. but yeah, it would be nice not to have to specify FC_BINARY in any case when 'registering' custom types..

**Comment by tlocke** [comment]
I've put a version of pg8000 up that has support for custom types:

https://github.com/tlocke/pg8000/tree/adapters 

There are examples at:

https://github.com/tlocke/pg8000/tree/adapters#custom-adapter-from-a-python-type-to-a-postgresql-type
https://github.com/tlocke/pg8000/tree/adapters#custom-adapter-from-a-postgresql-type-to-a-python-type

Let me know what you think :-)

**Comment by tlocke** [comment]
pg8000 adapters are in master now, so I'll mark this as closed.
