### ISSUE TITLE
Connection Refused when connecting to Tableau Server Database (Postgre) while working for other postgres databases

### ISSUE THREAD

**Issue by rgandhi2712** [tlocke/pg8000#39]
Hi All,

I am using this package to simply connect to a tableau server database using readonly credentials. Using pg8000.connect() command in python I am able to establish connection to other Postgres and Redshift databases but it keeps failing for Tableau Server repository with following error:
Error:
pg8000.core.InterfaceError: ('communication error', ConnectionRefusedError(61, 'Connection refused'))

Any update would be helpful. Thanks in advance!

**Comment by tlocke** [comment]
Hi @rgandhi2712, can you connect to the server using a different client, eg. psql, using the same settings (host, port etc) ?

**Comment by rgandhi2712** [comment]
Yes tlocke,

Using the exact same script I am able to connect to Tableau Server Database using psycopg2 python package and even via workbench like SQLWorkbench/J, etc.

**Comment by tlocke** [comment]
I've released a new version 1.15.3 https://github.com/tlocke/pg8000#version-1-15-3-2020-06-14 that should give a better error message (and also uses the higher-level socket.create_connection function). So if you try again, and it still doesn't work, can you paste in the full error message and stack trace?
