### ISSUE TITLE
Statement timeout when creating function

### ISSUE THREAD

**Issue by 4word** [tlocke/pg8000#41]
When creating a function, the statement always time out for some reason. Creating the same function using psql works as expected, and takes less than 100ms. I am unsure of why this happens, and i am hopeful its because I am missing something in the documentation.

```
some_trigger_function = """CREATE OR REPLACE FUNCTION test_trigger_function()
  RETURNS trigger AS
$BODY$
  BEGIN
    RETURN NEW;
  END
$BODY$
LANGUAGE plpgsql;"""

con = pg8000.connect("postgres", password="test", port=15432, database="test", timeout=10)

# This works as expected
con.run("SELECT * FROM pg_catalog.pg_class;")

# I tried this with autocommit as well as without, although it shouldnt make a difference
con.autocommit = True

# This statement always times out, or if I don't define the timeout, will run forever (~30 minutes before I killed it)
con.run(some_trigger_function)
```

**Comment by 4word** [comment]
Tested on both postgresql 10.7 and latest 11

**Comment by tlocke** [comment]
Hi @4word, I'm afraid I couldn't reproduce your bug (using PostgreSQL 12 and pg8000 1.16.1). Can you try using pg8000 1.16.1 if you weren't before?

**Comment by tlocke** [comment]
I'm afraid I couldn't reproduce your bug. However, if it's still a problem please do re-open the issue and we can try and delve in to what's causing it.
