### ISSUE TITLE
'IN %s' (array) does not work

### ISSUE THREAD

**Issue by srepmub** [tlocke/pg8000#42]
the following works with psycopg2, but not with pg8000:

t = ['blue', 'green']
c.execute('DELETE FROM tag WHERE tag IN %s', (t,))

this leads to a ProgrammingError very similar to the one in issue 26 (which was closed because no follow up).

I'm not sure yet what psycopg2 sends to the server here, but it's possible it checks the length of t and changes the query to something like '.. IN (%s, %s)', (t[0], t[1]).

**Comment by srepmub** [comment]
I checked the postgresql logs, and apparently psycopg2 fills in the parameters by itself, whereas pg8000 sends placeholders and parameters. postgresql does not like 'IN $2' and gives a syntax error.

**Comment by co60ca** [comment]
Use `any` like in this example:
https://github.com/tlocke/pg8000/blob/master/test/test_query.py#L208

Seems weird that it isn't supported.

**Comment by tlocke** [comment]
I've added an example for this in the README https://github.com/tlocke/pg8000#in-and-not-in

@srepmub Thanks for reporting it, and I agree with your analysis, it's a quirk of the server and not much can be done except use @co60ca's workaround.

@co60ca Thanks for pointing out the workaround, I've included it in a modified form in the README.
