### ISSUE TITLE
SQL against table name with capital letters

### ISSUE THREAD

**Issue by skemppin** [tlocke/pg8000#43]
I need to use tables with capital letters in them. 
How can I to use those tables with pg8000 ?

for example:
con.run("SELECT count(*) FROM "Table_Name"")
gives error:
SyntaxError: invalid syntax

**Comment by tlocke** [comment]
Hi @skemppin, try doing something like:

`con.run('''SELECT count(*) FROM "Table_Name"''')`

I've written a little note on it at: https://github.com/tlocke/pg8000#quoted-identifiers-in-sql
