### ISSUE TITLE
scramp 1.2.0 released 

### ISSUE THREAD

**Issue by itamarjp** [tlocke/pg8000#44]
theres a new version scramp 1.2.0

https://github.com/tlocke/scramp/releases

setup.py says

    install_requires=['scramp==1.1.1'],

I think its need's to be ajusted to make pg8000 compatible with newer scramp

**Comment by tlocke** [comment]
Thanks @itamarjp, I've made that change now https://github.com/tlocke/pg8000/commit/71f1378a2bf007ada3e2695ff269abffd69775c9
