### ISSUE TITLE
Run .sql files using pg8000

### ISSUE THREAD

**Issue by maddy2u** [tlocke/pg8000#45]
pg8000 is a great library. However, it doesnt' give the opportunity for the users to run multiple sql statements sequentialls in a .sql file. This results in having multiple sql statements hardcoded in the python file and is difficult to read and manage.

**Comment by tlocke** [comment]
Hi @maddy2u, does this help at all ? https://github.com/tlocke/pg8000#execute-sql-files

**Comment by maddy2u** [comment]
Hi,

Yes, it helps.. But don't you think it can be incorporated within the library - makes it easier. Do you want me to give it a shot?

**Comment by tlocke** [comment]
Yes, I think you're right, it should be a core part of the library. I think we can achieve it by using the [Simple Query](https://www.postgresql.org/docs/current/protocol-flow.html#id-1.10.5.7.4) message flow. This avoids prepared statements, and so we can have multiple statements in the SQL.

**Comment by tlocke** [comment]
With the latest release of pg8000 https://github.com/tlocke/pg8000/commit/a64cf55128789e823057a8bce69205b5c19ac83d you can execute multiple SQL statements directly.
