### ISSUE TITLE
Support for notification payloads

### ISSUE THREAD

**Issue by StefanVidakovic** [tlocke/pg8000#49]
Hi, just wondering if there's plans for adding support for notification payloads. Currently, Connection.notifications only stores a tuple of (postgres PID, channel name). [The postgres notify command](https://www.postgresql.org/docs/current/sql-notify.html) supports payloads as well. While there are probably numerous ways one might leverage this I particularly find it useful for being notified not only when something was inserted into the db, but also to be informed of the contents of the insertion. If there are no plans to work on this I am happy to contribute. Thanks.

Regards
Stefan

**Comment by tlocke** [comment]
That's a good idea @StefanVidakovic. I've added this on a test branch https://github.com/tlocke/pg8000/tree/test. Let me know if you like it and I'll put it on `master`.

**Comment by StefanVidakovic** [comment]
Looks awesome! Thank you!
