### ISSUE TITLE
IN/NOT IN

### ISSUE THREAD

**Issue by FedericoMassaioli** [tlocke/pg8000#54]
Hi,
I apologize if this has already been raised and discussed.

In the [IN and NOT IN](https://github.com/tlocke/pg8000#in-and-not-in) documentation section the use of ANY and ALL is suggested instead of IN and NOT IN in presence of parameters.
However, to my understanding this could result in a suboptimal query plan, like not using indexes.

The following alternative works (using the same synthetic query example which of course does not uses indexes at all! just imagine a real query) and builds the scenario that PostgreSQL better manages:

```
>>> con.run("SELECT 'silo 1' WHERE 'a' IN (SELECT unnest(:v))", v=('a', 'b'))
(['silo 1'],)
```

Ditto for NOT IN.

Are there any downside in this approach?

**Comment by tlocke** [comment]
That's a great suggestion @FedericoMassaioli! I've updated the docs accordingly https://github.com/tlocke/pg8000#in-and-not-in

**Comment by FedericoMassaioli** [comment]
Thanks, @tlocke.
Anyhow, I wouldn't remove the ANY/ALL example altogether, I'd keep it as an alternative, just making users know that, depending on the specific query, the mileage may vary.

BTW, I'm really enjoying pg8000.
