### ISSUE TITLE
AWS IAM authentication ... where do I reference a certificate

### ISSUE THREAD

**Issue by pieterbergmans** [tlocke/pg8000#57]
Hi...I'm following [this AWS tutorial](https://aws.amazon.com/blogs/database/iam-role-based-authentication-to-amazon-aurora-from-serverless-applications/) to connect my lambda function to my Aurora postgres DB.  The article is from Sep, 2019 and it looks like it references an ```ssl``` parameter that pg8000 doesn't support any longer. 

```
conn = pg8000.connect(
            host=DBEndPoint,
            user=DBUserName,
            database=DatabaseName,
            password=password,
            ssl={"sslmode": "verify-full", "sslrootcert": "rds-ca-2015-root.pem"},
        )
```

I realize that I need to use ```ssl_context=True``` instead but my question is, where do I specify ```sslmode``` and ```sslrootcert```?  When I use ```ssl_context=True``` in the above ```pg8000.connect()``` call, I get the following error: ```('Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed '
 '(_ssl.c:852)')```

I was able to connect via the following ```psql``` command so I know that everything works.  

```
psql "sslrootcert=utils_layer/python/rds-ca-2019-root.pem host=mydbinstance.us-east-1.rds.amazonaws.com port=5432 sslmode=verify-full user=devuser password=$(aws rds generate-db-auth-token --hostname mydbinstance.us.us-east-1.rds.amazonaws.com --port 5432 --username devuser --region us-east-1) dbname=mydb”
```

Any suggestions would be a great help!

Thanks.

**Comment by tlocke** [comment]
Hi @pieterbergmans, looking at the [docs](https://github.com/tlocke/pg8000#functions), `ssl_context` can have one of three values:

* None, meaning no SSL (the default)
* True, means use SSL with an ssl.SSContext created using ssl.create_default_context()
* An instance of ssl.SSContext which will be used to create the SSL connection.

In your case you need the third option where `ssl_context` is an instance of [ssl.SSContext](https://docs.python.org/3/library/ssl.html#ssl.SSLContext).

I think we probably need to add an example of this in the docs. I haven't got time to write it right now so I'll leave this issue open as a reminder.

**Comment by pieterbergmans** [comment]
Thanks @tlocke for getting me on the right path.  For those who find themselves on this threat, here is my final code:

```
        client = boto3.client('rds')        
        db_pass = client.generate_db_auth_token(
            DBHostname=db_host,
            Port=db_port,
            DBUsername=db_user,
            Region='us-east-1'
        )        
       
        ssl_context = ssl.SSLContext()
        ssl_context.verify_mode = ssl.CERT_REQUIRED
        ssl_context.load_verify_locations(os.path.join(__location__, '../rds-ca-2019-root.pem'))        

        conn = pg8000.connect(
            database=db_name, 
            user=db_user, 
            password=db_pass, 
            host=db_host,
            port=db_port,  
            ssl_context=ssl_context                   
            ) 
```

**Comment by tlocke** [comment]
Thanks for this @pieterbergmans, I've added in a couple of SSL examples at https://github.com/tlocke/pg8000#connect-to-postgresql-over-ssl
