### ISSUE TITLE
Could not determine data type of parameter

### ISSUE THREAD

**Issue by zicokuo** [tlocke/pg8000#60]
sqlalchemy.exc.ProgrammingError: (pg8000.exceptions.ProgrammingError) {'S': 'ERROR', 'V': 'ERROR', 'C': '42P18', 'M': 'could not determine data type of parameter $1', 'F': 'postgres.c', 'L': '1350', 'R': 'exec_parse_message'}

[SQL: SELECT count(%s) AS count_1 

FROM user_account]

[parameters: ('*',)]

**Comment by tlocke** [comment]
Hi @zicokuo, a suggestion would be to use a `cast` in the SQL so that Postgres knows that the parameter is a string.

**Comment by tlocke** [comment]
Hopefully you got this working in the end @zicokuo. If not, please feel free to re-open the issue.
