### ISSUE TITLE
scram channel binding bug

### ISSUE THREAD

**Issue by tlocke** [tlocke/pg8000#63]
I can't get scram channel binding to work. If you can help, have a look at:

https://github.com/tlocke/pg8000/blob/master/pg8000/core.py

and search for `make_channel_binding` and there's a note in the code. I know https://github.com/michaelpq is an expert in this area.

**Comment by Neustradamus** [comment]
Good job from @tlocke in scramp!

**Comment by tlocke** [comment]
Thanks @Neustradamus :-) So this bug is fixed now with commit: https://github.com/tlocke/pg8000/commit/3bdf2d08b78ffeb3ed3dd7b78a36a93258e9545f
