### ISSUE TITLE
Documentation refers to SSLConnect as SSConnect

### ISSUE THREAD

**Issue by jekozyra** [tlocke/pg8000#66]
The documentation [here](https://github.com/tlocke/pg8000#functions) refers to `SSLConnect` as `SSConnect` - however it links to the right place.

**Comment by tlocke** [comment]
Thanks for pointing this out @jekozyra, I've fixed it with https://github.com/tlocke/pg8000/commit/c471e4dc64a631395960cfaad02983132bfa9b5a
