### ISSUE TITLE
Last release on Pypi broke Python2.7 deployments

### ISSUE THREAD

**Issue by piroux** [tlocke/pg8000#7]
Hi!

First, I would like to thank you for maintaining this project and taking the time to migrate it toward Python3. :+1:
At work, we are in the process of migrating our stack to Python3, but we have got a significant part of the stack still on Python2.7. So like everybody forced to migrate to Python3 this year, the migration is ongoing, but it will take some time. :man_factory_worker:
Moreover, it was a chance that this package was compatible with Python 2 and Python 3 at the same time previously. However the last release on Pypi `1.13.0` broke that nice cohabitation, hence this issue.

#### Expected result
- :black_square_button: As of today and in a foreseeable future, a Python3 project, which would have your package as a dependency, would select the latest release available of `pg8000` on Pypi, which should be `1.13.0` or any future releases of your package.
For instance, installing your package through with `pip` for Python3.6 should yield the following packages list:
```
$ ./venv3/bin/pip install pg8000
[...]
$ ./venv3/bin/pip list
Package             Version
------------------- -------
passlib             1.7.1  
pg8000              1.13.0 
pip                 19.0.1 
setuptools          40.7.3 
six                 1.12.0 
wheel               0.32.3 
```
- :black_square_button: As of today and in a foreseeable future, a Python2.7 project, which would have your package as a dependency, would select the last release available of `pg8000` on Pypi, compatible with Python2.7. As of today, it should be `1.12.4` on January 5th on Pypi, and given that you dropped the support for Python with your last release, we may assume that a Python2.7 setup should select a version of your package matching `>=1.12.4, <1.13`.
For instance, installing your package through with `pip` for Python2.7 should yield the following packages list:
```
$ ./venv2/bin/pip install pg8000
[...]
$ ./venv2/bin/pip list
Package             Version
------------------- -------
pg8000              1.12.4 
pip                 19.0.1 
setuptools          40.7.3 
six                 1.12.0 
wheel               0.32.3 
```

#### Actual result
- :heavy_check_mark:  As of today, a Python3 project, which would have your package as a dependency, would select the latest release or any future available on Pypi. Today, it would be `1.13.0`. It works as expected.
- :stop_sign: **As of today, a Python2.7 project, which would have your package as a dependency, would select the last release available on Pypi, `1.13.0`, which is not compatible with Python2.7.** Actually, the worse part is that it will install it correctly but it will only fail later, at import time.

#### Context
My test workflow for Python 2.7 includes using the `testing.postgresql` package which is dependent on your `pg8000` package as a pure Python implementation PostgreSQL driver, but I did not know that until yesterday. Now I am well aware of it ;)

The `testing.postgresql` package is currently maintaining the compatibility for Python 2.7 and Python3 (it might change soon I assume) but it is not their role to select the version of `pg8000` in their `setup.py`. 
The root cause of the problem is that you just released a new `pg8000` version on Pypi which is only compatible with Python3. Precisely you actually uploaded a wheel which is marked as only compatible with Python3, but it seems that you also uploaded the source archive for this release.

#### Why is it an issue?
As you may know, Python2.7 will reach its EOL at the end of 2019 and the entire Python ecosystem is undergoing a migration effort to either migrate directly from Python2 to Python3 or to drop the Python2 support they had been forced to maintain for so many years, like your package. That is a good thing. In the meantime, during this transition year, it would be a good gesture from package maintainers to not break Python 2 projects deployments that do not rely on pining requirements for their deployments. Indeed, after setting up a virtualenv for Python2.7, and installing the package with `pip install <packagename>` only, **`pip` should always be able to select the latest release of the package, compatible with the target version of Python of the virtualenv.**

And this is the root of the issue here because currently, the pip for Python2.7 will believe that your `1.13.0` release is a good fit.

For a more detailed explanation, I am only considering setups with recent `pip` and `setuptools`:

- As of today, if someone is using your package for a Python3 project, and has already added `pg8000` in the `requirement.txt` or through the `test_requires`/`install_requires` `setuptools` option, it will work, because it will select your last released `wheel`, and everything will be installed, imported and run just fine.

- But if someone is using your package for a Python2.7 project, and has already added `pg8000` in the `requirement.txt` or through the `test_requires`/`install_requires` `setuptools` option, it will break at import time because the `setup.py` of your last release is compatible with Python2.7, but the source code of the package is not, obviously:
```
env/local/lib/python2.7/site-packages/testing/postgresql.py:17: in <module>
    import pg8000
env/local/lib/python2.7/site-packages/pg8000/__init__.py:1: in <module>
    from pg8000.core import (
env/local/lib/python2.7/site-packages/pg8000/core.py:23: in <module>
    from datetime import timezone as Timezone
E   ImportError: cannot import name timezone
```
The reason is that, as of today, `pip` is going to select the source archive of your last release on Pypi which is marked as compatible with all Python versions. Note that specifying the Python version in the `classifiers` option, like you already did, is not sufficient to help `pip` decide which version to select from your Pypi repo.

### Resolution goal
For a Python2.7 project, in order for `pip` to be able to select the right release from Pypi, it needs to know that your `1.13.x` releases are not compatible and that it has to look at "older" releases, in a semantic versioning way.
To that end, specifying the Python versions you are supporting in a package, become almost mandatory to let users transition smoothly to Python3. That's what the `python_requires` option of `setuptools` is supposed to do in the `setup.cfg`/`setup.py` file.
Finally, from now on, the upload of new releases should be done through a tool which can export those python requirements metadata. Indeed the command `python setup.py upload` is not handling the packaging metadata correctly. So that in order to upload to Pypi, `twine` should be used.
But it is not sufficient because following the semantic versioning, `pip` will continue to see the `1.13.0` as most recent and the previous steps do not prevent it to think otherwise. So this release should be deleted from your Pypi, otherwise, it will forever shadow all `1.12.x` releases for Python2.7.

To sum up, the resolution steps, which I offer you, would entail:
- releasing a new `pg8000/1.12.5` for Python 2.7 and 3.5+
- releasing a new `pg8000/1.13.1` for Python 3.5+ only
- deleting the `pg8000/1.13.0` release from Pypi.

**The goal of the resolutions steps is to make `pip` based on Python2.7 or Python3 select the right release automatically without actually selecting a particular version, only by leveraging setuptools/Pypi semantics.**

### Resolution steps
**STEP 1.** Release distribution of `1.12.5` for Python 2.7 and 3.5+
- Create a git branch for the last Python2.7 compatible version of the package, checked out at the commit `5318879` matching your `1.12.4` tag and release (actually `7809779` would be better I think for a new Python2.7 release) even if you do not plan to maintain it.
- In this 2.7 branch, according to the classifiers that I see, add:
    - `python_requires='>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*',` in the `setup` function of the `setup.py` file,
    - or  `python_requires = >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*` in the `options` section of the `setup.cfg` file.
- Commit the changes and tag it (for versionneer) with `1.12.5`
- Create a source and universal wheel dist:
`(venv2.7) $ python2.7 setup.py sdist bdist_wheel --universal`
- Upload it to Pypi as a new release:
`(venv2.7) $ twine upload dist/*`

**STEP 2.**  Release distribution of `1.13.1` for Python 3.5+ only
- Come back to your master branch (to include potential new changes since `1.13.0`) or to the `b3cbbf6` commit matching your `1.13.0` tag and release (actually this is more difficult  because it involves creating a new branch and then rebasing your master branch on top of this new branch and push-force on origin/master)
- According to the classifiers that I see, add:
    - `python_requires='>=3.5',` in the `setup` function of the `setup.py` file,
    - or  `python_requires = >=3.5` in the `options` section of the `setup.cfg` file.
- Commit the changes and tag it (for `versionneer`) with `1.13.1`
- Create a source and wheel dist for python 3 only:
`(venv3.5) $ python3.5 setup.py sdist bdist_wheel --python-tag py3`
- Upload it to Pypi as a new release:
`(venv3.5) $ twine upload dist/*`

**STEP 3.** Deletion of the `1.13.0` release from Pypi.
- Open https://pypi.org/manage/project/pg8000/releases/
- Find the row of the `1.13.0` release
- Manage, Detele, Confirm

## Final words
I know that was a long read, but I wanted to convince you why it would be a good idea to issue two new releases, one of which for a version of Python you rightly decided to stop supporting.

Again, thank you very much for maintaining this package, and I look forward to seeing it used in Python3 projects, including mine, as well.

---

For reference:
- https://www.python.org/dev/peps/pep-0345/#requires-python
- https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
- Pytest is planning to use this `setuptools` feature to let Python2.7 users automatically install the most recent`pytest` Python2.7 compatible. You can see it already present in their [ `setup.cfg`](https://github.com/pytest-dev/pytest/blob/2264db7f4a9b5cf339a77882584ad55673adca24/setup.cfg#L46)
https://docs.pytest.org/en/latest/py27-py34-deprecation.html
   > We plan to drop support for Python 2.7 and 3.4 at the same time with the release of pytest 5.0, scheduled to be released by mid-2019. Thanks to the python_requires setuptools option, Python 2.7 and Python 3.4 users using a modern pip version will install the last compatible pytest 4.X version automatically even if 5.0 or later are available on PyPI.
- https://stackoverflow.com/questions/40114100/uploading-different-versions-python-2-7-vs-3-5-to-pypi
- https://stackoverflow.com/questions/19534896/enforcing-python-version-in-setup-py/48777286#48777286

**Comment by tlocke** [comment]
Thanks for this @piroux, I think it's the most comprehensive issue I've ever seen! I've taken your advice and everything should be working correctly now. I'll close the issue, but please do re-open it if it's not working properly.
