### ISSUE TITLE
DatabaseError never raised?

### ISSUE THREAD

**Issue by gekorob** [tlocke/pg8000#70]
Hi all,
   I'm using pg8000 directly in my google cloud functions (not wrapped by SQLAlchemy) and looking at the source code to understand better the library I can see from a comment in `pg8000.exceptions` that `DatabaseError` is never raised
 
https://github.com/tlocke/pg8000/blob/75f10fb4d541fabd21054c21e2d5ed90a152cf2a/pg8000/exceptions.py#L27

Is that true?

Looking at the code in 

https://github.com/tlocke/pg8000/blob/75f10fb4d541fabd21054c21e2d5ed90a152cf2a/pg8000/core.py#L340-L344

and at the implementation of `handle_ERROR_RESPONSE`

https://github.com/tlocke/pg8000/blob/75f10fb4d541fabd21054c21e2d5ed90a152cf2a/pg8000/core.py#L354-L361

it seems to me that the `DatabaseError` can be raised. Am I wrong?

Thanks for any explanation and for your great work of course.

**Comment by tlocke** [comment]
Ooops, you're quite right, I've now removed that comment in https://github.com/tlocke/pg8000/commit/80751e457bf805f4e2ed2c87c6e7027301c332a8 Thanks for pointing it out.

**Comment by gekorob** [comment]
@tlocke thanks a lot
