### ISSUE TITLE
Parameter type inference can break on lists of ints when values have large magnitude differences

### ISSUE THREAD

**Issue by jamadden** [tlocke/pg8000#71]
I was testing RelStorage against pg8000 1.19.2 and [ran into this issue](https://github.com/zodb/relstorage/issues/438#issuecomment-825116452); it wasn't a problem with 1.16, which was the previous tested version.

There I found that calling  `cursor.execute("DELETE FROM object_ref WHERE tid = ANY (%s)" [0, 279098040260880896, 279098040260852974, 279098040260818483])` would fail with this error:

```
pg8000.dbapi.ProgrammingError: {'S': 'ERROR', 
   'V': 'ERROR', 
   'C': '22003', 
   'M': 'value "279098040260880896" is out of range for type smallint', 
   'F': 'numutils.c', 'L': '241', 'R': 'pg_strtoint16'}
```

Tracing the code, this winds up in `pg8000.converters.array_inspect`, which gets the first element of the list and uses that to determine the OID of the type: https://github.com/tlocke/pg8000/blob/80751e457bf805f4e2ed2c87c6e7027301c332a8/pg8000/converters.py#L611-L621

That in turn wound up passing `0` to `inspect_int` which concludes that 0 is a `SMALLINT` and so that's the type that's used. That's not big enough for the other ints though, so we wind up with this error. https://github.com/tlocke/pg8000/blob/80751e457bf805f4e2ed2c87c6e7027301c332a8/pg8000/converters.py#L585-L587

I only ever use lists as parameters when they contain integers (of various sizes), so I was able to find a workaround by doing `connection.py_types[list] = (BIGINT_ARRAY, int_array_out)`.

**Comment by tlocke** [comment]
Hi @jamadden, thanks for the bug report. I've fixed this now in release 1.19.3, but let me know if you have any more problems.
