### ISSUE TITLE
Loosen the constraints for scramp dependency

### ISSUE THREAD

**Issue by jaklan** [tlocke/pg8000#74]
As for now, `pg8000` specifies very conrete version of `scramp`:
https://github.com/tlocke/pg8000/blob/485f77f99c2c79f9b735bb9995b0df0de95dec8a/setup.py#L36
The only thing differentiating version 1.4.0 from 1.3.0 is an additional ScrampException:
>Version 1.4.0, 2021-03-28
Raise an exception if the client receives an error from the server.

which, scanning quickly through the codebase, doesn't seem to be a dependency for `pg8000`.

That creates issues in libraries like `awswrangler` from AWS depending on both `pg8000` and e.g. `redshift-connector`:
https://github.com/awslabs/aws-data-wrangler/issues/704

**Comment by tlocke** [comment]
I can see this immediate problem is solved, but to help things in the future I've put the dependency on scramp as a `>=` rather than `==`.
