### ISSUE TITLE
Missing release / tag for 1.20.0

### ISSUE THREAD

**Issue by jayaddison** [tlocke/pg8000#77]
Hi @tlocke - it looks like the release tag for 1.20.0 might be missing from the repository?  (I noticed it as the latest version available on PyPi)

**Comment by tlocke** [comment]
Thanks for pointing that out @jayaddison, that should be fixed now. I'm getting slack in my old age :-)

**Comment by jayaddison** [comment]
No worries - release management is tricky :)

And yep, I see that version tag now - thanks @tlocke!
