### ISSUE TITLE
Allow arbitrary connection arguments

### ISSUE THREAD

**Issue by pfhayes** [tlocke/pg8000#8]
Postrges has a long list of potentially desirable connection arguments (for example, https://www.postgresql.org/docs/9/libpq-connect.html), but it doesn't appear to be possible to include those, only the ones that have been specifically implemented (like `application_name`)

It would be great if they could be passed in to the `Connection` class and forwarded on to the backend

It looks like this connection string would need to be extended with new arguments (https://github.com/tlocke/pg8000/blob/69430edd49a8fdc549eadf5070b855425451af9f/pg8000/core.py#L1418) - is that correct?

**Comment by tlocke** [comment]
@pfhayes I think this is a good idea, so I've implemented it at: https://github.com/tlocke/pg8000/commit/357a3c31b0d885e51706365ad859004902ad5319
