### ISSUE TITLE
AttributeError calling executemany with empty parameter set

### ISSUE THREAD

**Issue by GKTheOne** [tlocke/pg8000#82]
Exception when calling Cursor.executemany with an empty param_sets iterator.
`AttributeError: 'NoneType' object has no attribute 'row_count'`
https://github.com/tlocke/pg8000/blob/1.21.1/pg8000/legacy.py#L304

**Comment by tlocke** [comment]
Hi @GKTheOne, thanks for reporting this. I've released version 1.21.2 in which the bug should be fixed. I'll close this issue for now, but please do re-open if it's still a problem.
