### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by carlkid1499** [tlocke/pg8000#83]
Hello There,

I am having an issue using the latest version of pg8000. I am on version 1.21.2. This is the error  I am encountering:
![image](https://user-images.githubusercontent.com/27721404/134998460-1282ad24-9e9f-44c1-9d4a-eb5c320f1144.png)

I tried downgrading to 1.20.0 and ran the same python 3 script. On 1.20.0 my script runs fine. I then tried 1.21.0 and 1.21.1. It also fails with the same error as 1.21.2. Has anything major changed since 1.20.0 ?

Let me know if more information is needed.

thanks!

**Comment by tlocke** [comment]
Hi @carlkid1499, thanks for reporting the bug. What would be really helpful is if you could provide a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by carlkid1499** [comment]
With version 1.20.0
![image](https://user-images.githubusercontent.com/27721404/135128060-40ece20f-60af-4930-9309-89b086269a26.png)

With version 1.21.2
![image](https://user-images.githubusercontent.com/27721404/135128350-9395d6ff-596d-4ce5-b289-7993a0010f98.png)

This is the test script
[test_pg8000.zip](https://github.com/tlocke/pg8000/files/7245980/test_pg8000.zip)
:

**Comment by tlocke** [comment]
Thanks, I managed to reduce it even further to:

```
import pg8000


con = pg8000.connect(user="postgres", password="pw")

ps = con.prepare("ROLLBACK")
ps.run()

```

and it's now fixed in https://github.com/tlocke/pg8000/commit/b6afc494afdfb38ee13ac2468ee07045454eb83c
