### ISSUE TITLE
Does pg8000 support the Redshift super column type?

### ISSUE THREAD

**Issue by blucas** [tlocke/pg8000#86]
To begin with, I apologize if this isn't the correct place to ask this question.

I'm trying to understand if pg8000 will correctly support extracting values from columns whose datatype is  from Redshift's [SUPER](https://docs.aws.amazon.com/redshift/latest/dg/r_SUPER_type.html) type.

Right now when I execute a query, the value representing the column I am interested in if of type `str` and I was expecting it to be a `list`.  I am executing a query very similar to [this one](https://docs.aws.amazon.com/redshift/latest/dg/split_to_array.html). In fact you can use that to test:

```python
cursor.execute("SELECT split_to_array('12|345|6789', '|')").fetchall()
```
As I understand it.  This should return a single row with a single column.  That column should contain an array of numbers, but instead, the column is the string representation of a json array

**Comment by tlocke** [comment]
Hi @blucas, I'm afraid Redshift isn't officially supported by pg8000. Redshift is a fork from Postgres from about version 8 IIRC and so pg8000 may or may not work with it. So I don't know the answer to the question, but someone else might...

**Comment by tlocke** [comment]
I'll close this issue for now, but feel free to re-open if needed.
