### ISSUE TITLE
Starting in v1.22.0, there is a failure to insert integer fields that are not perfectly typed

### ISSUE THREAD

**Issue by daveandtaye** [tlocke/pg8000#97]
Verified that there was no issue in 1.21.3, but starting in 1.22.0, I get an error raised when the input value from the data frame is not a clean integer type.  For example, if the input value is "8.0" or "0E-10", it fails with the stack trace below but worked fine prior to 1.22.0.

` File "/root/.local/lib/python3.8/site-packages/pg8000/legacy.py", line 302, in executemany
    self.execute(operation, parameters)
  File "/root/.local/lib/python3.8/site-packages/pg8000/legacy.py", line 277, in execute
    raise cls(msg)
pg8000.dbapi.ProgrammingError: {'S': 'ERROR', 'V': 'ERROR', 'C': '22P02', 'M': 'invalid input syntax for integer: "8.0"', 'F': 'numutils.c', 'L': '106', 'R': 'pg_atoi'}`

`  File "/root/.local/lib/python3.8/site-packages/pg8000/legacy.py", line 302, in executemany
    self.execute(operation, parameters)
  File "/root/.local/lib/python3.8/site-packages/pg8000/legacy.py", line 277, in execute
    raise cls(msg)
pg8000.dbapi.ProgrammingError: {'S': 'ERROR', 'V': 'ERROR', 'C': '22P02', 'M': 'invalid input syntax for integer: "0E-10"', 'F': 'numutils.c', 'L': '106', 'R': 'pg_atoi'}`

**Comment by tlocke** [comment]
I see the error now, before 1.22.0 the types of each parameter were specified by pg8000, and so for example if a float were sent then postgres would know it was a float and parse it as such, and know to convert it to the int column type. Starting in 1.22.0, pg8000 doesn't send types by default, and postgres assumes they're of the correct type, and gives an error if they can't be parsed as that type. So to avoid the error you could either send the matching type, or you could use the setinputsizes() function to specify the type you're sending explicitly.

**Comment by daveandtaye** [comment]
Thanks for your response.  Since sending the types is a major change for us, would you consider supporting an `unsafe_type_infer` flag or something similar to restore the behavior that previously existed?

**Comment by daveandtaye** [comment]
Thanks.  That works for a few places in our code where we know that we are targeting an integer column.  Our most common use case is that we are writing to an unknown set of tables and columns.  We'd now have to query database column metadata prior to inserting in order to see if we happen to have any integers we intend to write into.

**Comment by tlocke** [comment]
Actually, simpler still, forget about `setinputsizes()` and for every parameter where you don't know the column type, just send it as a `str`.

**Comment by daveandtaye** [comment]
Trying to understand your suggestion.  Not as a solution, but just as a test, I temporarily adjusted the pg8000 execute method like the following to see what happens if I send `pg8000.STRING` for all values.  It immediately failed when encountering a boolean value.

`def execute(self, operation, args=(), stream=None):
        try:
            if not self._c.in_transaction and not self._c.autocommit:
                self._c.execute_unnamed("begin transaction")

            statement, vals = convert_paramstyle(self.paramstyle, operation, args)

            ##################################
            self._input_oids = []
            for val in vals:
                self._input_oids.append(pg8000.STRING)
            ##################################

            self._context = self._c.execute_unnamed(
                statement, vals=vals, oids=self._input_oids, stream=stream
            )

            rows = [] if self._context.rows is None else self._context.rows
            self._row_iter = iter(rows)

            self._input_oids = ()`

**Comment by tlocke** [comment]
Yes you're right, sorry that idea doesn't work. Here's an example of something that should work:

```
from pg8000.native import BOOLEAN, Connection, FLOAT, INTEGER, STRING

con = Connection("postgres", password="cpsnow")

LOOKUP = {
    str: STRING,
    bool: BOOLEAN,
    int: INTEGER,
    float: FLOAT,
}

con.run("CREATE TEMPORARY TABLE a (id SERIAL, b BOOL, c INTEGER)")

params = {
    'b': True,
    'c': 0.1,
}

types = {(k, LOOKUP[type(v)]) for k, v in params.items()}

con.run("INSERT INTO a (b, c) VALUES (:b, :c)", **params, types=types)
```

I've used the `pg8000.native` API because the code is clearer, but the same should work with the `pg8000.dbapi` API. So basically what we're doing here is finding the type of each parameter, and then telling pg8000 the type to send to the server, then the server does the necessary conversion. This is what the old version of pg8000 did behind the scenes.

**Comment by tlocke** [comment]
I'll close this now, but please do re-open if needed.
