### ISSUE TITLE
Date type with infinity triggers ValueError

### ISSUE THREAD

**Issue by indyspike** [tlocke/pg8000#99]
When using a Date column type and a row containing 'infinity' for the value, the following error is generated.

> ValueError: time data 'infinity' does not match format '%Y-%m-%d'

A quick fix in converters.py is to add the lines that capture infinity from timestamp_in(data) to date_in(data). Not sure if this will cause issues elsewhere.

**Comment by tlocke** [comment]
Good idea @indyspike, I've done that and released it as version 1.24.1.

**Comment by tlocke** [comment]
This has been fixed so I'll close the issue, but do re-open if it's still a problem.
